// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Shortlr struct {
	ID          pgtype.UUID
	LongUrl     string
	ShortUrl    string
	AccessCount pgtype.Int8
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}
